//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssetManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Assignment
    {
        public int ID { get; set; }
        public int EmployeeID { get; set; }
        public Nullable<int> HardwareID { get; set; }
        public Nullable<int> SoftwareID { get; set; }
        public Nullable<int> VisioID { get; set; }
        public Nullable<int> StatusID { get; set; }
        public string Comment { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Hardware Hardware { get; set; }
        public virtual Software Software { get; set; }
        public virtual Software Software1 { get; set; }
    }
}
